import type { Metadata } from "next";
import { Geist, Geist_Mono,Inter } from "next/font/google";
import Navbar from '@/components/ui/Navbar';
import Footer from '@/components/ui/Footer'
import AnimatedBackground from '@/components/ui/AnimatedBackground';
import "./globals.css";
import MotionEffects from '@/components/ui/MotionEffects'
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={`${inter.className} bg-light`}>
                {/* 选择一种背景方案 */}
                {/* 添加硬件加速层 */}
                <div className="gpu-layer">
                    <AnimatedBackground />
                    <MotionEffects /> {/* 新增拖尾特效 */}
                </div>
                <div className="relative z-20 isolate">
                    <div className="absolute inset-0 -z-10 bg-light-80 backdrop-blur-lg"/>
                    <Navbar/>
                    <main className="pt-16">{children}</main>
                    <Footer/>
                </div>
            </body>
        </html>
    );
}
